# This file was generated by GoReleaser. DO NOT EDIT.
cask "emcogni" do
  name "emcogni"
  desc "AI-powered context engine CLI for developer workflows"
  homepage "https://emcogni.com"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "emcogni"

  on_macos do
    on_intel do
      url "https://github.com/embedded-cognizance/emcogni-code-release/releases/download/v#{version}/emcogni_#{version}_darwin_amd64.tar.gz"
      sha256 "8916660e3ec2ba3d486b27f11794c415e1954d11ccc2a366dd6701c47ba5c878"
    end
    on_arm do
      url "https://github.com/embedded-cognizance/emcogni-code-release/releases/download/v#{version}/emcogni_#{version}_darwin_arm64.tar.gz"
      sha256 "51a35f790b425a0ed49c52739d24354f86afb0fabc0731d641aa1adecea9826b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/embedded-cognizance/emcogni-code-release/releases/download/v#{version}/emcogni_#{version}_linux_amd64.tar.gz"
      sha256 "42b4ce5ab470c8f058bc1770d5fd7b653ab56f49ff24daadc4f81670be3607cc"
    end
    on_arm do
      url "https://github.com/embedded-cognizance/emcogni-code-release/releases/download/v#{version}/emcogni_#{version}_linux_arm64.tar.gz"
      sha256 "8ae4ccb0976cbaaef9df6740953b518767aa1c25cf500d6cc1f0743e8c81ad82"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/emcogni"]
    end
  end

  caveats do
    "emcogni stores context at ~/.emcogni (context.db + config.json)."
    "This data is not removed when you uninstall via brew."
    ""
    "To fully remove all emcogni data and then the binary:"
    "  emcogni uninstall"
    "  brew uninstall emcogni"
  end

  # No zap stanza required
end
