# This file was generated by GoReleaser. DO NOT EDIT.
cask "emcogni" do
  name "emcogni"
  desc "AI-powered context engine CLI for developer workflows"
  homepage "https://emcogni.com"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "emcogni"

  on_macos do
    on_intel do
      url "https://github.com/embedded-cognizance/emcogni-code-release/releases/download/v#{version}/emcogni_#{version}_darwin_amd64.tar.gz"
      sha256 "fbecde15b9e30cf0f00b2d599cbd34ad0c39101219c716914a2555533204fde6"
    end
    on_arm do
      url "https://github.com/embedded-cognizance/emcogni-code-release/releases/download/v#{version}/emcogni_#{version}_darwin_arm64.tar.gz"
      sha256 "9553cadc161d720fa75a59646d26d114b796f6c5d748c5a256e4d818f235cf9f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/embedded-cognizance/emcogni-code-release/releases/download/v#{version}/emcogni_#{version}_linux_amd64.tar.gz"
      sha256 "12b20a4b4d60399221939118530b4f4709f45a0c4f922a255d867ef60da21f32"
    end
    on_arm do
      url "https://github.com/embedded-cognizance/emcogni-code-release/releases/download/v#{version}/emcogni_#{version}_linux_arm64.tar.gz"
      sha256 "b85dc9ac77c1becb018d5421c7bc9d1f33263f00dd16f8fc3bd9b3e44c2b4633"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/emcogni"]
    end
  end

  caveats do
    "emcogni stores context at ~/.emcogni (context.db + config.json)."
    "This data is not removed when you uninstall via brew."
    ""
    "To fully remove all emcogni data and then the binary:"
    "  emcogni uninstall"
    "  brew uninstall emcogni"
  end

  # No zap stanza required
end
