# This file was generated by GoReleaser. DO NOT EDIT.
cask "emcogni" do
  name "emcogni"
  desc "AI-powered context engine CLI for developer workflows"
  homepage "https://emcogni.com"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "emcogni"

  on_macos do
    on_intel do
      url "https://github.com/embedded-cognizance/emcogni-code-release/releases/download/v#{version}/emcogni_#{version}_darwin_amd64.tar.gz"
      sha256 "cc5ca2ed88e7f3b61628ed3f8c346aa9e703dff51a74fddbad6b5b9af376d01d"
    end
    on_arm do
      url "https://github.com/embedded-cognizance/emcogni-code-release/releases/download/v#{version}/emcogni_#{version}_darwin_arm64.tar.gz"
      sha256 "97459062a396ffce472cb1a3e8fd469d1ebc731af192b6c75604b3f9dae7f407"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/embedded-cognizance/emcogni-code-release/releases/download/v#{version}/emcogni_#{version}_linux_amd64.tar.gz"
      sha256 "3673d9d3332a51b8f92b0a86aaa88bfcde11f56a48334cdfdf98a2d20189ef17"
    end
    on_arm do
      url "https://github.com/embedded-cognizance/emcogni-code-release/releases/download/v#{version}/emcogni_#{version}_linux_arm64.tar.gz"
      sha256 "11480d1585711ae3ee992d614a724983de58d0f8f11c43b9a4f397ebd0872505"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/emcogni"]
    end
  end

  caveats do
    "emcogni stores context at ~/.emcogni (context.db + config.json)."
    "This data is not removed when you uninstall via brew."
    ""
    "To fully remove all emcogni data and then the binary:"
    "  emcogni uninstall"
    "  brew uninstall emcogni"
  end

  # No zap stanza required
end
