# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Emcogni < Formula
  desc "AI-powered context engine CLI for developer workflows"
  homepage "https://emcogni.com"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/embedded-cognizance/emcogni-code-release/releases/download/v0.1.0/emcogni_0.1.0_darwin_amd64.tar.gz"
      sha256 "36899ea374d86d7fbb5f9052364764be0dd29b669a7bcb8a3918f8f82acb549b"

      def install
        bin.install "emcogni"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/embedded-cognizance/emcogni-code-release/releases/download/v0.1.0/emcogni_0.1.0_darwin_arm64.tar.gz"
      sha256 "893771c1d195ec78679e6a6a0911212ca923c43a7b34e13987044fb63fa083b1"

      def install
        bin.install "emcogni"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/embedded-cognizance/emcogni-code-release/releases/download/v0.1.0/emcogni_0.1.0_linux_amd64.tar.gz"
      sha256 "bfec892b637b978e5caa7e271a15b68d22a6ad309ecf0570f05a965997687990"
      def install
        bin.install "emcogni"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/embedded-cognizance/emcogni-code-release/releases/download/v0.1.0/emcogni_0.1.0_linux_arm64.tar.gz"
      sha256 "c02b2afac4ba7bec9fa3460868b0d03a21025143ed2f37a52baf0a43b31cd6b5"
      def install
        bin.install "emcogni"
      end
    end
  end

  def caveats
    <<~EOS
      emcogni stores context at ~/.emcogni (context.db + config.json).
      This data is not removed when you uninstall via brew.

      To fully remove all emcogni data and then the binary:
        emcogni uninstall
        brew uninstall emcogni
    EOS
  end

  test do
    system "#{bin}/emcogni", "--version"
  end
end
