# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Emcogni < Formula
  desc "AI-powered context engine CLI for developer workflows"
  homepage "https://emcogni.com"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/embedded-cognizance/emcogni-code-release/releases/download/v0.1.0/emcogni_0.1.0_darwin_amd64.tar.gz"
      sha256 "22028179fbd2ac6f2f8549b49397b6a999cadf9d72d0c6554ae513ebac849231"

      def install
        bin.install "emcogni"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/embedded-cognizance/emcogni-code-release/releases/download/v0.1.0/emcogni_0.1.0_darwin_arm64.tar.gz"
      sha256 "14bcf6e0e3a95aad49ef6ec56d1697534d88102e69b163043a4ca1cecd59d0c3"

      def install
        bin.install "emcogni"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/embedded-cognizance/emcogni-code-release/releases/download/v0.1.0/emcogni_0.1.0_linux_amd64.tar.gz"
      sha256 "348f86537b995e4bde1a534e0f6a683f1a504db1774788f3324932fe5e823aab"
      def install
        bin.install "emcogni"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/embedded-cognizance/emcogni-code-release/releases/download/v0.1.0/emcogni_0.1.0_linux_arm64.tar.gz"
      sha256 "4dbfa17822a6765407692c55482370dc490841f26c1b491597e2a58c672ea044"
      def install
        bin.install "emcogni"
      end
    end
  end

  def caveats
    <<~EOS
      emcogni stores context at ~/.emcogni (context.db + config.json).
      This data is not removed when you uninstall via brew.

      To fully remove all emcogni data and then the binary:
        emcogni uninstall
        brew uninstall emcogni
    EOS
  end

  test do
    system "#{bin}/emcogni", "--version"
  end
end
