# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Emcogni < Formula
  desc "AI-powered context engine CLI for developer workflows"
  homepage "https://emcogni.com"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/embedded-cognizance/emcogni-code-release/releases/download/v0.1.0/emcogni_0.1.0_darwin_amd64.tar.gz"
      sha256 "7f2bedea6cf7a152114b64b9c73b721e48fd2945e42c1e39133b5c878bf907bc"

      def install
        bin.install "emcogni"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/embedded-cognizance/emcogni-code-release/releases/download/v0.1.0/emcogni_0.1.0_darwin_arm64.tar.gz"
      sha256 "021c60ad4af4e41916ee54e010124f0ab7faba2b4c3c10465f8448da5738f8fa"

      def install
        bin.install "emcogni"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/embedded-cognizance/emcogni-code-release/releases/download/v0.1.0/emcogni_0.1.0_linux_amd64.tar.gz"
      sha256 "e15e86b48f54d41713027f870d56e28e121a7ab9b87d0d7551ab0c422c2a89ab"
      def install
        bin.install "emcogni"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/embedded-cognizance/emcogni-code-release/releases/download/v0.1.0/emcogni_0.1.0_linux_arm64.tar.gz"
      sha256 "f08340b82df3628c38910a86f39b3fd53ad9c9a526d792e5202582462cb3664e"
      def install
        bin.install "emcogni"
      end
    end
  end

  def caveats
    <<~EOS
      emcogni stores context at ~/.emcogni (context.db + config.json).
      This data is not removed when you uninstall via brew.

      To fully remove all emcogni data and then the binary:
        emcogni uninstall
        brew uninstall emcogni
    EOS
  end

  test do
    system "#{bin}/emcogni", "--version"
  end
end
